### ISSUE TITLE
Please can add Alerta to send notifications

### ISSUE THREAD

**Issue by CyberAbwehr** [johnsusek/praeco#330] opened 2021-03-15 10:45 UTC
doc: https://elastalert.readthedocs.io/en/latest/ruletypes.html#alerta

Rulefile Example:

alert:
  - alerta
alerta_api_url: "http://192.168.0.10:8180/api/alert"
alerta_api_key: "jsadgkasjdgakjsdgaskjdgaskjdgasdkjg"
alerta_severity: "critical"
alerta_text: 'Docker Container CPU fully occupied'
alerta_event: 'Docker Container CPU fully occupied'
alerta_group: 'OS'

best regards

**Comment by nsano-rururu** [comment] 2021-03-15 10:59
@CyberAbwehr

Is there any problem with the following specifications for the UI of the setting screen? Please point out any mistakes.

|config| default value |input|remark|
|------|---------------|------|------|
|alerta_api_url|None|el-input|Required|
|alerta_api_key|None|el-input|Optional|
|alerta_timeout|86400|el-input-number|Optional|
|alerta_use_match_timestamp|false|el-switch |Optional|
|alerta_use_qk_as_resource|false|el-switch |Optional|
|alerta_api_skip_ssl|false|el-switch |Optional|
|alert_missing_value|'<MISSING VALUE>'|el-input|Optional|
|alerta_severity|'warning'|el-select<br>unknown, security, debug, informational, ok, normal, cleared, indeterminate, warning, minor, major, critical|Optional|
|alerta_resource|'elastalert'|el-input|Optional|
|alerta_environment|'Production'|el-input|Optional|
|alerta_origin|'elastalert'|el-input|Optional|
|alerta_service||list。UI to add / update / delete key|Optional|
|alerta_text|'elastalert'|el-input|Optional|
|alerta_type|'elastalert'|el-input|Optional|
|alerta_event|'elastalert'|el-input|Optional|
|alerta_correlate||list。UI to add / update / delete key|Optional|
|alerta_tags||[list。UI to add / update / delete key|Optional|
|alerta_group|''|el-input|Optional|
|alerta_attributes_keys||list。UI to add / update / delete key|Optional|
|alerta_attributes_values||list。UI to add / update / delete value|Optional|
|alerta_value|''|el-input|Optional|

**Comment by nsano-rururu** [comment] 2021-03-15 13:01
Will work on the following branches
https://github.com/johnsusek/praeco/tree/alerta_support

**Comment by nsano-rururu** [comment] 2021-03-15 13:05
@CyberAbwehr

I would like to know if all items are supported or if only the following items in the first post are supported for the time being.

```yaml
alerta_api_url: "http://192.168.0.10:8180/api/alert"
alerta_api_key: "jsadgkasjdgakjsdgaskjdgaskjdgasdkjg"
alerta_severity: "critical"
alerta_text: 'Docker Container CPU fully occupied'
alerta_event: 'Docker Container CPU fully occupied'
alerta_group: 'OS'
```

**Comment by CyberAbwehr** [comment] 2021-03-15 13:36
I have know following components installed to make test.

elastic: 7.10.2
praeco: 1.7.0
Alerta API: 8.4.1

Rule File:

![Bildschirmfoto 2021-03-15 um 14 32 00](https://user-images.githubusercontent.com/51229037/111161253-3a54e780-859b-11eb-893f-c8d2f6462ce9.png)

Normal I put following keys into the BaseConfig.json file
alerta_api_url: 
alerta_api_key: 

Output Alerta:

![Bildschirmfoto 2021-03-15 um 14 25 20](https://user-images.githubusercontent.com/51229037/111160590-881d2000-859a-11eb-8044-2f1d4f673f29.png)

**Comment by nsano-rururu** [comment] 2021-03-15 13:40
@CyberAbwehr

Please answer the question.

**Comment by CyberAbwehr** [comment] 2021-03-15 13:48
In the past some of the values have not worked, in the list that you post.
Maybe there are some changes now in the new Alerta version.

Following Values I have test and they are working:

alerta_api_url: 
alerta_api_key:
alerta_severity:
alerta_resource:
alerta_text:
alerta_event:
alerta_group:
alerta_tags:

**Comment by nsano-rururu** [comment] 2021-03-15 13:51
@CyberAbwehr

thank you for your answer. We will start to make it possible to set the items you contacted.

alerta_api_url:
alerta_api_key:
alerta_severity:
alerta_resource:
alerta_text:
alerta_event:
alerta_group:
alerta_tags:

**Comment by nsano-rururu** [comment] 2021-03-15 16:14
@CyberAbwehr

If there is no problem on the screen below, merge it with master and release it as 1.8.0.
https://github.com/johnsusek/praeco/tree/alerta_support

![1](https://user-images.githubusercontent.com/22293449/111184766-a31c7e00-85f4-11eb-81d7-71c1a0bf48aa.PNG)
![2](https://user-images.githubusercontent.com/22293449/111184782-a6b00500-85f4-11eb-89f2-0fb986b1a4c9.PNG)
![3-0](https://user-images.githubusercontent.com/22293449/111184798-aadc2280-85f4-11eb-9c70-007fa97fe911.PNG)
![3](https://user-images.githubusercontent.com/22293449/111184822-b0396d00-85f4-11eb-8aad-e6b43c145f8f.PNG)

**Comment by CyberAbwehr** [comment] 2021-03-15 16:24
Looks perfect ;-)

**Comment by nsano-rururu** [comment] 2021-03-15 17:47
Praeco has released a new docker image. 1.8.0
https://hub.docker.com/r/praecoapp/praeco

**Comment by CyberAbwehr** [comment] 2021-03-16 13:27
THX for the new version.

I have made some tests today.

Some notes:

- alerta_severity
    all severities needs to be defined in the alertad.conf configuration file.
    Standard definitions is: 
    fatal, critical, major, minor, warning, indeterminate, cleared, normal, ok, informational, debug, trace, unknown

- alert_text_args: [] & alert_subject_args: []

    where can i define this values in the GUI ?
    I need that to define as example alerts like

    alert_subject: "The following file {} has been {} on the {}"
    alert_subject_args:
        - file.path
        - event.action
        - agent.hostname

    alert_text: "The following file {} has been {} on the {}"
    alert_text_args:
        - file.path
        - event.action
        - agent.hostname

    alerta_severity: "minor"
    alerta_resource: '{agent[hostname]}'
    alerta_text: 'The following file {file[path]} has been {event[action]} on the {agent[hostname]}'
    alerta_event: '{file[path]} {event[action]}'
    alerta_group: 'Security'

- alert_text_type:
    is it possible to have the option to disable this value in the GUI?
    because I want to send the full original alert information.

best regards

**Comment by CyberAbwehr** [comment] 2021-03-16 13:55
Please can you add the value alerta_environment
THX

best regards

**Comment by nsano-rururu** [comment] 2021-03-16 13:57
Say it from the beginning. what is it. Do not be silly. Later this and this too. Not possible this week. I am busy with my work

**Comment by CyberAbwehr** [comment] 2021-03-16 14:12
THX for your feedback.

Sorry for all my comments, I only start testing to rebuild my rules with the new GUI.
I figured out that I use a lot of functions from elastalert in the past to build reasonable Alerts.

So take your time, am happy to see that this project is good maintened !!! :-) :-) :-) 

best regards

My notes:

- alerta_severity
    all severities needs to be defined in the alertad.conf configuration file.
    Standard definitions is: 
    fatal, critical, major, minor, warning, indeterminate, cleared, normal, ok, informational, debug, trace, unknown

- alert_text_args: [] & alert_subject_args: []

    where can i define this values in the GUI ?
    I need that to define as example a values like

    alert_subject: "The following file {} has been {} on the {}"
    alert_subject_args:
        - file.path
        - event.action
        - agent.hostname

    alert_text: "The following file {} has been {} on the {}"
    alert_text_args:
        - file.path
        - event.action
        - agent.hostname

    alerta_severity: "minor"
    alerta_resource: '{agent[hostname]}'
    alerta_text: 'The following file {file[path]} has been {event[action]} on the {agent[hostname]}'
    alerta_event: '{file[path]} {event[action]}'
    alerta_group: 'Security'

- alerta_environment
    please can you add this value 

- Some information to the alerta application
    When an alert with the same environment-resource-event combination is received with the same severity, the alert is de-duplicated.

**Comment by nsano-rururu** [comment] 2021-03-16 14:30
https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml#L357

alerta_new_style_string_format and alerta_customer are not used. There are two alerta_services. It doesn't hurt. It seems that schema.yaml is used to check the value when notifying the alert of the rule.
```yaml
 ### Alerta
  alerta_api_url: {type: string}
  alerta_api_key: {type: string}
  alerta_severity: {enum: [unknown, security, debug, informational, ok, normal, cleared, indeterminate, warning, minor, major, critical]}
  alerta_resource: {type: string}   # Python format string
  alerta_environment: {type: string}  # Python format string
  alerta_origin: {type: string}   # Python format string
  alerta_group: {type: string}  # Python format string
  alerta_service: {type: array, items: {type: string}}  # Python format string
  alerta_service: {type: array, items: {type: string}}  # Python format string
  alerta_correlate: {type: array, items: {type: string}}  # Python format string
  alerta_tags: {type: array, items: {type: string}}   # Python format string
  alerta_event: {type: string} # Python format string
  alerta_customer: {type: string}
  alerta_text: {type: string} # Python format string
  alerta_type: {type: string}
  alerta_value: {type: string} # Python format string
  alerta_attributes_keys: {type: array, items: {type: string}}
  alerta_attributes_values: {type: array, items: {type: string}}  # Python format string
  alerta_new_style_string_format: {type: boolean}
```

---

Customer's additional pull request
[Alerta: Add Customer in Alert Payload](https://github.com/Yelp/elastalert/pull/2269)

Alerta documentation pull request
[Update documentation for percentage_format_string and alerta_timeout](https://github.com/Yelp/elastalert/pull/2537)

Source code of the alerta part of elastalert
https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L1837

Alerta API Reference
https://docs.alerta.io/en/latest/api/reference.html

**Comment by nsano-rururu** [comment] 2021-03-16 17:36
Praeco & elastalert-server has released a new docker image.

alerta_environment(praeco) & time window(praeco & elastalert-server)
https://hub.docker.com/r/praecoapp/praeco
https://hub.docker.com/r/praecoapp/elastalert-server

**Comment by CyberAbwehr** [comment] 2021-03-17 08:09
THX for the newest Version

Adding fields for alerta are working

alerta_text: whoami process found on {agent[hostname]}
alerta_resource: "{agent[hostname]}"

In this case the agent.hostname is SRVV-M-CPT-T

![Bildschirmfoto 2021-03-17 um 08 58 53](https://user-images.githubusercontent.com/51229037/111433847-17434880-86ff-11eb-853a-8375247c8e30.png)

Adding fields for alert subject and alert text are not working in my case, maybe I do not understand '%' for adding fields name. ;-)

![Bildschirmfoto 2021-03-17 um 09 03 06](https://user-images.githubusercontent.com/51229037/111434247-9f295280-86ff-11eb-8823-330631f5e1de.png)

![Bildschirmfoto 2021-03-17 um 09 04 05](https://user-images.githubusercontent.com/51229037/111434379-c54ef280-86ff-11eb-9311-afe7d244d3e3.png)

I made a test with adding field names direct into rule.yml file.

alert_text: |
  {}
alert_text_args: [ "agent.hostname" ]

and it works

![Bildschirmfoto 2021-03-17 um 09 08 10](https://user-images.githubusercontent.com/51229037/111434918-6d64bb80-8700-11eb-83c7-00315c0846d2.png)

**Comment by nsano-rururu** [comment] 2021-03-17 10:47
Is it possible to use without single quotes before and after% instead of'%' before the field name? .. I don't think you need a single quote

**Comment by nsano-rururu** [comment] 2021-03-17 10:47
I haven't tried "%", so I don't know if it's a function that can still be used.

**Comment by nsano-rururu** [comment] 2021-03-17 10:50
The output of yaml uses js-yaml. I have specified double coating in the output settings, but I don't know if I can control whether or not to enclose it with double coating until I check it, and I don't know if it can be dealt with immediately.

**Comment by nsano-rururu** [comment] 2021-03-17 10:54
There seems to be an option "forceQuotes: true" in js-yaml, so I'll try it.

**Comment by nsano-rururu** [comment] 2021-03-17 11:02
There are no plans to release it for the time being, so even if we can handle it, we will not release it immediately.

**Comment by CyberAbwehr** [comment] 2021-03-17 11:23
I understand.

It is possible to add values like you have it done for Tags at Alerta?

alerta_tags:
  - threat

alert_subject_args:
- agent.hostname

alert_text_args:
- agent.hostname

best regards

**Comment by nsano-rururu** [comment] 2021-03-17 11:38
@CyberAbwehr 

Correspondence is possible

**Comment by nsano-rururu** [comment] 2021-03-17 12:55
@CyberAbwehr

I started with the corresponding version of praeco without saving it again, and confirmed that it will be surrounded by double quotes when yaml is loaded without saving.
When alert_subject_args and alert_text_args are supported, we will release them together. As 1.8.2.
![キャプチャ](https://user-images.githubusercontent.com/22293449/111470363-1d6f0e80-876b-11eb-8ed4-304f1024b632.PNG)

**Comment by nsano-rururu** [comment] 2021-03-17 13:21
If you want to be able to set it in the same way as alerta_tags, the following functions will be an obstacle and will be abolished.
If you try to use both, you will likely create a bug ...

**alert_text_args**

```
Test <span data-at-embedded="" contenteditable="false"> <span class="el-tag el-tag--info el-tag--mini" data-term="message">message<!----></span> </span>&nbsp;<div><br></div><div>123</div><div>&nbsp;b<span data-at-embedded="" contenteditable="false"> <span data-v-2d7a3f54="" class="el-tag el-tag--info el-tag--mini" data-term="@timestamp">@timestamp<!----></span> </span>&nbsp;aa</div><br><div>foo</div><div><br></div><div>bar</div><div><br></div><div>--baz</div>
```

**alert_subject_args**

```
Test <span data-at-embedded="" contenteditable="false"> <span class="el-tag el-tag--info el-tag--mini" data-term="message">message<!----></span> </span>&nbsp;<div><br></div><div>123</div><div>&nbsp;b<span data-at-embedded="" contenteditable="false"> <span data-v-2d7a3f54="" class="el-tag el-tag--info el-tag--mini" data-term="@timestamp">@timestamp<!----></span> </span>&nbsp;aa</div><br><div>foo</div><div><br></div><div>bar</div><div><br></div><div>--baz</div>
```

**Comment by nsano-rururu** [comment] 2021-03-18 17:17
@CyberAbwehr

Is there any problem with the following feeling? .. If there is no problem, it will be released as 1.8.2.
![1](https://user-images.githubusercontent.com/22293449/111668271-eecf6180-8858-11eb-9a0a-cff89a4450fe.PNG)
![2](https://user-images.githubusercontent.com/22293449/111668280-f131bb80-8858-11eb-9b03-987f659d47b8.PNG)
![3](https://user-images.githubusercontent.com/22293449/111668291-f2fb7f00-8858-11eb-86c1-db4a89113ad3.PNG)

**Comment by CyberAbwehr** [comment] 2021-03-18 17:28
Looks great, THX :-)

The args are processed one after the other,
what does that mean that the first curve brackets {} are arg 1, the second curve brackets {} are arg 2.
this means original there are no enumerations 0 then 1 insight the curve brackets {}.

**Comment by nsano-rururu** [comment] 2021-03-19 11:28
@CyberAbwehr

Praeco has released a new docker image.

Forced double quotes on yaml output & alert_subject_args / alert_text_args
https://hub.docker.com/r/praecoapp/praeco

**Comment by nsano-rururu** [comment] 2021-03-23 11:20
Close once. Please reopen if there is a problem.

**Closed by nsano-rururu** 2021-03-23 11:20 UTC
Labels: enhancement

**Comment by CyberAbwehr** [comment] 2021-03-23 11:27
The system on which I am testing has hardware problems.
At the moment these are being fixed.
As soon as that is done i will test the last version. ;-)

**Comment by nsano-rururu** [comment] 2021-03-23 16:25
By the way, 1.8.3 has a bug, so it is being fixed.

**Comment by nsano-rururu** [comment] 2021-03-23 16:44
1.8.4 released.(fix multiple query keys)
https://hub.docker.com/r/praecoapp/praeco

**Comment by CyberAbwehr** [comment] 2021-03-31 07:59
I have test today the version 1.8.4 and it works perfect, THX :-)

![Bildschirmfoto 2021-03-31 um 09 47 58](https://user-images.githubusercontent.com/51229037/113110174-10402e00-9207-11eb-8660-ba1d872b72dc.png)

![Bildschirmfoto 2021-03-31 um 09 48 06](https://user-images.githubusercontent.com/51229037/113110200-16360f00-9207-11eb-8dc4-ede4020182c9.png)

![Bildschirmfoto 2021-03-31 um 09 48 18](https://user-images.githubusercontent.com/51229037/113110220-1df5b380-9207-11eb-9bca-05dda50f9835.png)

![Bildschirmfoto 2021-03-31 um 09 58 09](https://user-images.githubusercontent.com/51229037/113110703-ab390800-9207-11eb-9c64-0ef90de106ee.png)

![Bildschirmfoto 2021-03-31 um 09 40 47](https://user-images.githubusercontent.com/51229037/113110242-251cc180-9207-11eb-8a1a-117f828b3836.png)

![Bildschirmfoto 2021-03-31 um 09 51 42](https://user-images.githubusercontent.com/51229037/113110266-2b12a280-9207-11eb-86e6-0f5f81f25ca2.png)

![Bildschirmfoto 2021-03-31 um 09 52 04](https://user-images.githubusercontent.com/51229037/113110293-349c0a80-9207-11eb-838e-adf3054be530.png)


 __praeco_full_path: "customer/alertatest"
__praeco_query_builder: "{\"query\":{\"logicalOperator\":\"all\",\"children\":[]}}"
alert:
  - "alerta"
alert_subject: "agent.name: {} \_event.module: {} \_event.action: {}\_event.category: {} process.name:\_{} user.name:\_{}"
alert_subject_args:
  - "agent.name"
  - "event.module"
  - "event.action"
  - "event.category"
  - "process.name"
  - "user.name"
alert_text: "agent.name: {}  event.module: {}  event.action: {} event.category: {} process.name: {} user.name: {}\_"
alert_text_args:
  - "agent.name"
  - "event.module"
  - "event.action"
  - "event.category"
  - "process.name"
  - "user.name"
alerta_api_key: "^Bpa%i8_nCAc8fI4l9)nhn2EG2!@GJga"
alerta_api_url: "http://alerta-web:8080/api/alert"
alerta_environment: "Production"
alerta_event: "{event[module]}"
alerta_group: "Security"
alerta_resource: "{agent[name]}"
alerta_severity: "minor"
alerta_tags:
  - "threat"
alerta_text: "A critical process {process[name]} from the user {user[name]} is executed on {agent[name]} "
blacklist:
  - "nmap"
compare_key: "process.name"
filter:
  - query:
      query_string:
        query: "@timestamp:*"
generate_kibana_discover_url: false
import: "../BaseRule.config"
index: "auditbeat-*"
is_enabled: true
kibana_discover_from_timedelta:
  minutes: 10
kibana_discover_to_timedelta:
  minutes: 10
limit_execution: "*/1 * * * *"
match_enhancements: []
name: "alertatest"
realert:
  minutes: 0
slack_attach_kibana_discover_url: false
timestamp_field: "@timestamp"
timestamp_type: "iso"
type: "blacklist"
use_strftime_index: false

**Comment by nsano-rururu** [comment] 2021-03-31 10:28
@CyberAbwehr

Thank you for your confirmation. We will release 1.8.5 this weekend.
https://github.com/johnsusek/praeco/pull/337

**Comment by nsano-rururu** [comment] 2021-04-05 12:38
praeco 1.8.5 has been released. 
https://hub.docker.com/r/praecoapp/praeco
