### ISSUE TITLE
Alert log shows empty data 

### ISSUE THREAD

**Issue by talcoh2x** [johnsusek/praeco#209] opened 2020-06-02 16:43 UTC
![image](https://user-images.githubusercontent.com/34831587/83546373-36bf0b00-a509-11ea-805f-a1090336c79f.png)

**Comment by talcoh2x** [comment] 2020-06-02 16:44
ELK 7.x

**Comment by nsano-rururu** [comment] 2020-06-03 12:36
https://github.com/ServerCentral/elastalert-server/pull/3

**Comment by nsano-rururu** [comment] 2020-06-05 15:45
@johnsusek 

I have a pull request, but when will it be taken in? It is already confirmed that the operation has been confirmed and the problem is solved, so I would like you to import it, but is it feeling busy with another work? .. If there is anything I can do, I would like to help.

**Comment by johnsusek** [comment] 2020-06-08 18:03
Will try to take a look at this, sorry I haven't had much time to spend on praeco lately

**Comment by johnsusek** [comment] 2020-06-13 22:22
@talcoh2x This should be fixed in the latest release

**Closed by johnsusek** 2020-06-13 22:22 UTC
Labels: bug
