### ISSUE TITLE
Error posting HTTP Post alert - elastalert-server

### ISSUE THREAD

**Issue by karthiknagraj** [johnsusek/praeco#386] opened 2021-08-03 11:05 UTC
## 🐛 Summary
I am using praecoapp/elastalert-server:20210609 docker image. I have configured Alerta webhook  to receive an alert from elastalert server. Below is the rule file.
```

name: alertrule-1
type: any
index: fluentd*
timestamp_field: "@timestamp"
realert:
  minutes: 1
filter:
\- query:
    query_string:
      query: "Name: \"Example Alert Occurred\""
alert:
\- post:
    http_post_url: "http://localhost/api/webhooks/elastalert"
alert_text: "critical alert raised" 

```

Configuration used to connect to elasticsearch
```

rules_folder: /opt/elastalert/rules
run_every:
  seconds: 60
buffer_time:
  minutes: 5
es_host: localhost
es_port: 9200
es_username: example
es_password: example-password
writeback_index: elastalert_status
use_ssl: false
alert_time_limit:
  days: 2

```

I am seeing the below-shown error message while sending alerts to Alerta from elastalert-server
```

10:58:26.472Z ERROR elastalert-server:
    ProcessController:  ERROR:elastalert:Error while running alert http_post: Error posting HTTP Post alert: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost/api/webhooks/elastalert

```

## 👀 Steps

(Bug reproduction procedure)

1. Bring up elastalert server as a kubernetes deployment with the above-shown rule file configured to send alerts to Alerta
2. Generate a dummy log and send it to elasticsearch so that elastalert and trigger alert for this log

## 🆗 Expected
In kubernetes pod of elastalert-server, we should not see above shown error message.

**Comment by nsano-rururu** [comment] 2021-08-03 11:22
There is confirmation. Does `http://localhost/api/webhooks/elastalert` match that something is running on the web server (port: 80) on the same server as elastalert-server?

**Comment by nsano-rururu** [comment] 2021-08-03 11:23
Have you ever written on github? .. It's really hard to see. Is it on purpose?
https://docs.github.com/ja/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by nsano-rururu** [comment] 2021-08-03 11:26
Did you choose to use alerta Alerter?
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alerta

**Comment by nsano-rururu** [comment] 2021-08-03 11:28
As far as the error is seen, it seems that the error is not on the elastalert-server side of node.js, but on the elastalert2 side of python.

**Comment by nsano-rururu** [comment] 2021-08-03 11:29
We have not confirmed the operation with kubernetes, so please do so at your own risk.

**Comment by nsano-rururu** [comment] 2021-08-03 11:30
I don't have information about what kind of configuration file and what kind of command was executed. Do you really want to solve the problem?

**Comment by nsano-rururu** [comment] 2021-08-03 11:44
When you were using bitsensor / elastalert, did you do the same thing on k8s? .. Or is it the first time to run with k8s?

**Comment by nsano-rururu** [comment] 2021-08-03 11:48
How many master nodes and worker nodes are there in the k8s configuration? Or deploy it anywhere on the worker node. Please give me some more information. I'm not Esper.

**Comment by karthiknagraj** [comment] 2021-08-03 11:54
> There is confirmation. Does `http://localhost/api/webhooks/elastalert` match that something is running on the web server (port: 80) on the same server as elastalert-server?

Alerta will be using different port. it is not same as that of elastalert server

> Did you choose to use alerta Alerter?
> https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alerta

For our use case, we want to use http_post receiver https://elastalert2.readthedocs.io/en/latest/ruletypes.html#http-post to send alerts to alerta as an HTTP payload. I'm receiving the alert as well. but I'm getting the above shown error in elastalert-server

> As far as the error is seen, it seems that the error is not on the elastalert-server side of node.js, but on the elastalert2 side of python.

So, showed I open this issue in elastert2 ?

> When you were using bitsensor / elastalert, did you do the same thing on k8s? .. Or is it the first time to run with k8s?

Yes, We are using bitsensor on k8s for a while.

**Comment by karthiknagraj** [comment] 2021-08-03 12:01
> How many master nodes and worker nodes are there in the k8s configuration? Or deploy it anywhere on the worker node. Please give me some more information. I'm not Esper.

I'm using Kubernetes v1.18.3 and it has 1 master node and 3 worker nodes. elastalert-server is deployed on a worker node. Please let me know if any other information is required.

**Comment by nsano-rururu** [comment] 2021-08-03 12:04
The rule is executed from elastalert installed in the docker container of elastalert-server. That means it needs to be an address that can be accessed outside from the docker container. Can I access it on localhost?

**Comment by nsano-rururu** [comment] 2021-08-03 12:05
In other words, if you do not set the value of "localhost" to a value that can be accessed from the outside, it will be useless forever.

**Comment by nsano-rururu** [comment] 2021-08-03 12:10
>So, showed I open this issue in elastert2 ?

I just told you where it's happening. It's just a bad setting. You don't have to do that.

**Comment by karthiknagraj** [comment] 2021-08-03 12:11
Yes @nsano-rururu , It has an IP address to access from outside. Since that is a piece of sensitive information, I have replaced that with localhost for posting it here.

**Comment by nsano-rururu** [comment] 2021-08-03 12:12
I see, it's actually a global address, but is that wrong?

**Comment by nsano-rururu** [comment] 2021-08-03 12:15
In that case, it may be necessary to set up to access the external server from the k8s pod. With k8s settings.

**Comment by karthiknagraj** [comment] 2021-08-03 12:16
No, It is correct, I can access it. elastalert-server is able to send alerts to configured address as well. But I'm getting the above shown error message in elastalert.

**Comment by nsano-rururu** [comment] 2021-08-03 12:27
Is it possible to try to see if the problem occurs with a docker-only configuration instead of k8s?

**Comment by nsano-rururu** [comment] 2021-08-03 13:08
> No, It is correct, I can access it. elastalert-server is able to send alerts to configured address as well. But I'm getting the above shown error message in elastalert.

Rule execution is elastalert in the docker container of elastalert-server. I'm saying that elastalert-server can send, but that's a big mistake. elastalert-server alone does not notify alerts.

**Comment by nsano-rururu** [comment] 2021-08-03 13:21
When I put Mattermost on another server and it didn't work, I was rejected by the setting of the server with Mattermost. The OS of the server at that time is CentOS 8. At that time, I disabled SELinux. Therefore, it is necessary to isolate the problem where the problem is occurring.

**Comment by nsano-rururu** [comment] 2021-08-03 14:38
What happens when `http://localhost/api/webhooks/elastalert` is run by itself, for example with the curl command?

**Comment by nsano-rururu** [comment] 2021-08-03 14:40
It's alerta's webhook, but it looks like the setting used when forwarding alerts received by alerta to another system (slack, ms teams, etc.).

**Comment by nsano-rururu** [comment] 2021-08-03 14:44
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#alerta

**Comment by nsano-rururu** [comment] 2021-08-03 14:48
There is no information I can provide anymore, so I will close it. Open it when you find a solution.

**Closed by nsano-rururu** 2021-08-03 14:48 UTC
Labels: bug
