### ISSUE TITLE
Request for support to "hive" integration like telegram, slack (New feature)

### ISSUE THREAD

**Issue by iamk-karthik** [johnsusek/praeco#208] opened 2020-05-26 11:28 UTC
@johnsusek 
 Request for support to "hive" integration like telegram, slack (New feature)

**Comment by mdennison-ntc** [comment] 2020-05-29 16:13
I would also be interested in this

**Comment by nsano-rururu** [comment] 2020-09-13 14:13
@iamk-karthik 

I don't know about "hive" at all
Please let me know if you know the URL of the site that will be helpful in checking the operation of "hive". 
If possible, I would like to build an environment with docker-compose.yml.

**Comment by cvdjv** [comment] 2020-09-15 20:56
https://github.com/TheHive-Project/TheHive
https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

**Comment by nsano-rururu** [comment] 2020-09-16 12:54
@cvdjv 

Thank you

**Comment by pingkrimson** [comment] 2020-12-02 23:46
I would also be interested in this feature

**Comment by nsano-rururu** [comment] 2020-12-31 11:07
There are currently no plans to add hive alerts. The reason is that the development of ElastAlert seems to be over. 
It's no longer maintained as I've seen it.

**Comment by nsano-rururu** [comment] 2021-02-23 14:02
If you really want to support it, please write a concrete UI image.

https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive
- Hive_connection and hive_alert_config are required.
- The tag of hive_alert_config is a UI that allows you to add / change / delete multiple keywords.
- Hive_proxies is optional.
- I don't know what kind of setting the option hive_observable_data_mapping should be and what kind of UI should be used.

**Comment by nsano-rururu** [comment] 2021-02-27 06:12
I see, if you can't answer the question, you don't need to respond. Really.

**Comment by iamk-karthik** [comment] 2021-03-01 04:46
@nsano-rururu Thank you for bearing with my late reply.  I am not good in design.  But let me try and will give you the UI image.

**Comment by nsano-rururu** [comment] 2021-03-01 07:13
@iamk-karthik

Let's develop in another branch and proceed while cooperating by checking the screen image and output contents. I'm not good at designing either.

**Comment by nsano-rururu** [comment] 2021-03-01 09:55
@iamk-karthik

hive_observable_data_mapping is domain, domain, ip in the document, is this a fixed item? .. Please let me know if you know anything.
Perhaps it's a variable key, and you can specify multiple values in an array? .. I'm asking because I don't know about the hive at all.
https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive

```
hive_observable_data_mapping:
    - domain: "{match[field1]}_{rule[name]}"
    - domain: "{match[field]}"
    - ip: "{match[ip_field]}"
```

**Comment by nsano-rururu** [comment] 2021-03-01 09:57
@iamk-karthik

Please answer even if you do not understand. I don't know. In that case, add a UI that allows you to set the required hive_connection and hive_alert_config on the screen.

**Comment by iamk-karthik** [comment] 2021-03-01 10:05
I thing As like in telegram and email we need to have provision to add the following part(Which is common to all elast alert rules) of the hive configuration in **elastalert/rules/BaseRule.config** 

 **hive_connection:
   hive_host: http://localhost
   hive_port: <hive_port>
   hive_apikey: <hive_apikey>
   hive_proxies:
     http: ''
     https: ''**

The following may be given as configuration that varies with each rule. ( hive_alert_config )
![praeco_hive](https://user-images.githubusercontent.com/2486683/109481904-5fc5f980-7aa3-11eb-9450-7d54811cb7d2.png)

The existing configuration is looks as follows
![ref](https://user-images.githubusercontent.com/2486683/109482069-8c7a1100-7aa3-11eb-9f69-df7ded801626.png)

Thanks for understanding me neither an expert in hive sorry for that.

**Comment by iamk-karthik** [comment] 2021-03-01 10:07
@nsano-rururu 

> @iamk-karthik
> 
> hive_observable_data_mapping is domain, domain, ip in the document, is this a fixed item? .. Please let me know if you know anything.
> Perhaps it's a variable key, and you can specify multiple values in an array? .. I'm asking because I don't know about the hive at all.
> https://elastalert.readthedocs.io/en/latest/ruletypes.html#thehive
> 
> ```
> hive_observable_data_mapping:
>     - domain: "{match[field1]}_{rule[name]}"
>     - domain: "{match[field]}"
>     - ip: "{match[ip_field]}"
> ```

domain, domain, ip are not fixed items

**Comment by nsano-rururu** [comment] 2021-03-01 10:37
@iamk-karthik

hive_connection is BaseRule.config. hive_alert_config is set on the screen, isn't it? understood.
severity and tlp are numbers. Make the UI so that multiple tags can be registered. If follow is true and false, isn't it better to use radio buttons? Other than that, I will implement it as a character. Please point out if you make a mistake.
Details of the settings will be confirmed on thehive's official website at the time of implementation.

Example of setting thehive

```yaml
alert:
- hivealerter
 
hive_connection:
  hive_host: http://localhost
  hive_port: <hive_port>
  hive_apikey: <hive_apikey>
  hive_proxies:
   http: ''
   https: ''

hive_alert_config:
  title: 'Title'  ## This will default to {rule[index]_rule[name]} if not provided
  type: 'external'
  source: 'elastalert'
  description: '{match[field1]} {rule[name]} Sample description'
  severity: 2
  tags: ['tag1', 'tag2 {rule[name]}']
  tlp: 3
  status: 'New'
  follow: True
```

**Comment by nsano-rururu** [comment] 2021-03-01 10:39
@iamk-karthik

The hive_observable_data_mapping UI will take some time to implement, so I'll exclude it in the first release.

**Comment by nsano-rururu** [comment] 2021-03-01 10:59
tags will have the following UI
![108085362-991c6380-70b8-11eb-83e9-d606a95b31e0](https://user-images.githubusercontent.com/22293449/109488230-9d894900-7ac8-11eb-8aa3-98d939acf54b.png)

**Comment by nsano-rururu** [comment] 2021-03-01 12:10
I wonder if I will color the background color and make it a radio button
tlp is 0, 1, 2, 3 for WHITE, GREEN, AMBER, RED. Default: 2
severity is 1, 2, 3, 4 for LOW, MEDIUM, HIGH, CRTICAL. Default: 2
https://thehive-project.github.io/TheHive4py/reference/models/

**Comment by nsano-rururu** [comment] 2021-03-01 12:18
The following The Hive pull request fix will be included in the ElastAlertServer Docker image
https://github.com/Yelp/elastalert/pull/2891

**Comment by nsano-rururu** [comment] 2021-03-01 12:19
@iamk-karthik

All screen inputs are mandatory, right?

**Comment by nsano-rururu** [comment] 2021-03-01 12:29
follow is true or false. I'm going to use the following UI
>follow (boolean) : if true, the alert becomes active when updated default=true

false
![キャプチャ](https://user-images.githubusercontent.com/22293449/109497291-2d34f480-7ad5-11eb-97b5-4a64c2b0d01d.PNG)
true
![キャプチャ2](https://user-images.githubusercontent.com/22293449/109497293-2efeb800-7ad5-11eb-92e7-207cae6c76ee.PNG)

**Comment by nsano-rururu** [comment] 2021-03-01 12:32
Select status on the radio
>status (AlertStatus) : status of the alert (New, Updated, Ignored, Imported) default=New
https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/alert.md

**Comment by nsano-rururu** [comment] 2021-03-01 12:38
Are there also customFields? I don't support this time

```
"customFields": {
        "foo": {
            "order": 1,
            "string": "qlo msg 2"
        },
        "message": {
            "order": 0,
            "string": "qlo msg 1"
        }
    },
```

**Comment by iamk-karthik** [comment] 2021-03-01 12:45
> @iamk-karthik
> 
> hive_connection is BaseRule.config. hive_alert_config is set on the screen, isn't it? understood.
yes perfect..!
> severity and tlp are numbers. Make the UI so that multiple tags can be registered. If follow is true and false, isn't it better to use radio buttons? Other than that, I will implement it as a character. Please point out if you make a mistake.
Yes my mistake **severity & tlp** both are numbers, and I agree with **tags, follow remaining fields** implementation too..
> Details of the settings will be confirmed on thehive's official website at the time of implementation.
> 
> Example of setting thehive
> 
> ```yaml
> alert:
> - hivealerter
>  
> hive_connection:
>   hive_host: http://localhost
>   hive_port: <hive_port>
>   hive_apikey: <hive_apikey>
>   hive_proxies:
>    http: ''
>    https: ''
> 
> hive_alert_config:
>   title: 'Title'  ## This will default to {rule[index]_rule[name]} if not provided
>   type: 'external'
>   source: 'elastalert'
>   description: '{match[field1]} {rule[name]} Sample description'
>   severity: 2
>   tags: ['tag1', 'tag2 {rule[name]}']
>   tlp: 3
>   status: 'New'
>   follow: True
> ```

Thank you..!

**Comment by iamk-karthik** [comment] 2021-03-01 12:46
> @iamk-karthik
> 
> The hive_observable_data_mapping UI will take some time to implement, so I'll exclude it in the first release.

Yes I agree.

**Comment by iamk-karthik** [comment] 2021-03-01 12:54
> @iamk-karthik
> 
> All screen inputs are mandatory, right?

I didn't checked this 

> @iamk-karthik
> 
> All screen inputs are mandatory, right?

No not.  Though without which the case creation at Hive side don't give information.

**Comment by nsano-rururu** [comment] 2021-03-01 13:29
>No not. Though without which the case creation at Hive side don't give information.

understood. However, when creating a new rule, the default values of the Hive formula are selected for severity, tlp, status, and follow.

Although it is not written in the document, it seems that there is a setting called "hive_verify". Default "False"
Since it seems to be written in hive_connection, "hive_verify" announces that it will be written in BaseRule.config at the time of release.

https://github.com/Yelp/elastalert/blob/master/elastalert/alerts.py#L2175
>verify = connection_details.get('hive_verify', False)

**Comment by nsano-rururu** [comment] 2021-03-04 17:02
@iamk-karthik

Is it okay to look like this?

![1](https://user-images.githubusercontent.com/22293449/110000414-9b3c1e80-7d56-11eb-9028-db035b6c77a4.PNG)
![2](https://user-images.githubusercontent.com/22293449/110000431-9e370f00-7d56-11eb-982d-7d07c7a0fc17.PNG)
![3](https://user-images.githubusercontent.com/22293449/110000441-a131ff80-7d56-11eb-8167-329b2227dea7.PNG)
![4](https://user-images.githubusercontent.com/22293449/110000452-a4c58680-7d56-11eb-953b-ca2bcec46203.PNG)
![5](https://user-images.githubusercontent.com/22293449/110000462-a727e080-7d56-11eb-9d28-ad19788f9719.PNG)
![6](https://user-images.githubusercontent.com/22293449/110000469-a98a3a80-7d56-11eb-9aee-09d26e916d73.PNG)

**Comment by iamk-karthik** [comment] 2021-03-05 06:35
> @iamk-karthik
> 
> Is it okay to look like this?
> 
> ![1](https://user-images.githubusercontent.com/22293449/110000414-9b3c1e80-7d56-11eb-9028-db035b6c77a4.PNG)
> ![2](https://user-images.githubusercontent.com/22293449/110000431-9e370f00-7d56-11eb-982d-7d07c7a0fc17.PNG)
> ![3](https://user-images.githubusercontent.com/22293449/110000441-a131ff80-7d56-11eb-8167-329b2227dea7.PNG)
> ![4](https://user-images.githubusercontent.com/22293449/110000452-a4c58680-7d56-11eb-953b-ca2bcec46203.PNG)
> ![5](https://user-images.githubusercontent.com/22293449/110000462-a727e080-7d56-11eb-9d28-ad19788f9719.PNG)
> ![6](https://user-images.githubusercontent.com/22293449/110000469-a98a3a80-7d56-11eb-9aee-09d26e916d73.PNG)

yes please..!

**Comment by nsano-rururu** [comment] 2021-03-05 08:55
@iamk-karthik

Released as Praeco 1.7.0. We plan to update both Praeco and elastalert-server Docker images to include the hive patch in the elastalert-server docker image. I will contact you again with this issue when the release work is finished. At that time, close this issue.

**Comment by nsano-rururu** [comment] 2021-03-05 17:29
@iamk-karthik

We have released and released a new docker image, so this issue will be closed.

**Closed by nsano-rururu** 2021-03-05 17:29 UTC
Labels: enhancement

**Comment by iamk-karthik** [comment] 2021-03-11 04:56
> @iamk-karthik
> 
> We have released and released a new docker image, so this issue will be closed.

Thank you so much @nsano-rururu...!
